
services:
  mysql:
    image: mysql:latest
    container_name: library-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    networks:
      - backend

  book-service:
    build: ./book-service
    container_name: book-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
